package culture;
import java.util.*;
// In the following, a program construct is on the left, and what it refers to is on the right.
// The items on the right should be translated, if they are not already.
public class InteractTexts_de_DE extends ListResourceBundle {
  static final Object[][] contents = {
        { "copyright", "Java Interact 2, � 2001, David Heise." },
        { "sentenceSeparation", ". " },
        { "clauseSeparation", ", " },
        { "colon", ":" },
        { "space", " " },
        { "comma", "," },
        { "point", "." },
        { "tab", "\t" },
        { "leftBracket", "[" },
        { "rightBracket", "]" },
        { "paragraphCommand", "\n" },
        { "continuing", "Continuing with " },
        { "helpType", new String[] {"Hilfe", "Einleitung", "Kulturen", "Interagierende", "Situation definieren", "Interaktion definieren",
                "Interaktion analysieren", "W�rter finden", "Emotionen und Rollen", "Selbst explorieren", "Interact Gleichungen",
                "Simulationsergebnisse", "Im- und Exportieren", "Einstellungen"}},
// The next item, helpURL, should not be translated.
       { "helpURL", new String[] {"", "Introduction.html", "Cultures.html", "Interactants.html", "Situation.html", "Events.html",
                "Analyzing.html", "Concepts.html", "Emotions.html", "Selves.html", "Equations.html", "Report.html",
                "Import.html", "Options.htm"}},
        { "operationType", new String[] {"Einstellungen", "Interaktionsteilnehmer benennen", "Selbst explorieren", "Situation definieren", "Interaktion definieren", "Interaktion analysieren",
                                    "W�rter finden", "Emotionen und Rollen", "Gleichungen ansehen", "Eintr�ge importieren", "Ergebnisprotokoll"}},
        { "displayType", new String[] {"Basisfunktionen", "Fortgeschrittene Funktionen"}},
// The next item, cultureType, should not be translated.
        { "cultureType", new String[] {"Indiana 2003", "Texas 1998", "North Carolina 1978", "Ontario Canada 1981", "Ontario Canada 2001",
                "N. Ireland 1977", "Germany 1989", "Japan 1989-2002", "China-PRC 1991", "Deutsch Germany", "Deutsch Germany07"}},
        { "evaluation", "E" },
        { "potency", "P" },
        { "activity", "A" },
        { "namingLabel", "Name" },
        { "biologyLabel", "Geschlecht" },
        { "languageLabel", "Sprache" },
        { "controllingLabel", "Controlling" },
        { "personText", "Person " },
        { "selfText", "Selbst" },
        { "named", "genannt" },
        { "raterSex", "Geschlecht der Rater" },
        { "viewer", "F�r Beobachter" },
        { "male", "m�nnlich" },
        { "female", "weiblich" },
        { "theSettingIs", "in der Situation" },
        { "thePersonIs", "ist" },
        { "institution", "Institution" },
        { "combination", "Kombination" },
        { "actor", "Akteur" },
        { "behavior", "Handlung" },
        { "object", "Objektperson" },
        { "obj", "Objektperson" },
        { "setting", "Kontext" },
        { "prior", "Benutze vorherige Handlungen" },
        { "unfoldOptimal", "Automatische dyadische Interaktion" },
        { "insert", "Diese Handlung implementieren" },
        { "behaviorMeaning", new String[] {"Kein wiederholendes Verhalten","Bedeutung des Verhaltens beibehalten","Bedeutung des Verhaltens ver�ndert sich"}},
        { "experiences", "Wahrnehmung von" },
        { "actorEmotions", "Emotionen des Akteurs" },
        { "objectEmotions", "Emotionen der Objektperson" },
        { "actorBehaviors", "Optimale Handlung des Akteurs" },
        { "present", "momentanes" },
        { "future", "kommendes" },
        { "objectBehaviors", "Erwartete Reaktion der Objektperson" },
        { "actorAttributes", "Attribute des Akteurs" },
        { "objectAttributes", "Attribute der Objektperson" },
        { "actorLabels", "Wer w�rde sich so verhalten" },
        { "objectLabels", "Wen w�rde man so behandeln" },
        { "changeFiltersButton", "Filter" },
        { "emptyResults", "Keine ann�hernde Beschreibung vorhanden" },
        { "EPAprofile", "Suche Eintr�ge mit dem EPA Profil" },
        { "cutoffInstruction", "Maximale Entfernung angeben" },
        { "caseNames", new String[] {"Identit�ten", "Handlungen", "Pers�nlichkeit / Emotionen", "Situationen"} },
        { "identityFilters", new String[] {"M�nnlich", "Weiblich", "Privat", "Wirtschaft", "Recht", "Politik", "Universit�t", "Medizin", "Religion", "Familie", "", "Selbstbezogen", "Interaktiv", "K�rperlich"} },
        { "behaviorFilters", new String[] {"offen", "vermutet", "Privat", "Gesch�ftlich", "Recht", "Politik", "Universit�t", "Medizin", "Religion", "Familie", "", "Selbstbezogen", "Interaktiv", "K�rperlich"} },
        { "modifierFilters", new String[] {"Adjektive", "", "Emotionen", "Pers�nlichkeit", "Status", "Sonstige", "", "", "", "", "", "", "", ""} },
        { "settingFilters", new String[] {"Ort", "Zeit", "Privat", "Wirtschaft", "Recht", "Politik", "Universit�t", "Medizin", "Religion", "Familie", "", "Selbstbezogen", "Interaktiv", "K�rperlich"} },
        { "allFilters", "Alle" },
        { "settingTitle", "Situation" },
        { "fundamental", "Grundgef�hl" },
        { "transient", "Vor�bergehend" },
        { "equations", new String[] {"W�hlen Sie ein Gleichungssystem.", "M�nnlich Akteur-Handlung-Objektperson", "Weiblich Akteur-Handlung-Objektperson", "M�nnlich Akteur-Handlung-Objektperson-Kontext", "Weiblich Akteur-Handlung-Objektperson-Kontext", "M�nnlich selbstbezogene Handlung", "Weiblich selbstbezogene-Handlung", "M�nnlich Pers�nlichkeit-Identit�t", "Weiblich Pers�nlichkeit-Identit�t", "M�nnlich Emotion-Identit�t", "Weiblich Emotion-Identit�t"} },
        { "importEquationCoefficientsButton", "Die unteren Koeffizienten importieren" },
        { "maleRaters", "Daten von M�nnern" },
        { "femaleRaters", "Daten von Frauen" },
        { "solveFor", "Aufl�sen nach:" },
        { "actorIdentity", "Identit�t des Akters" },
        { "objectIdentity", "Identit�t der Objektperson" },
        { "actorMood", "Stimmung des Akteurs" },
        { "objectMood", "Stimmung der Objektperson" },
        { "characteristicEmotion", "Charakteristische Emotion"},
        { "givenActor", "Identit�t des Akteurs" },
        { "givenObject", "Identit�t der Objektperson" },
        { "actorSelf", "Selbst des Akteurs" },
        { "objectSelf", "Selbst der Objektperson" },
        { "thisBehavior", "Handlung" },
        { "compute", "L�sung berechnen" },
        { "individualAmalgamation", "Verschmolzener Affekt" },
        { "individualTransient", "Vor�bergehender Affekt" },
        { "selfProfile", "EPA Selbst" },
        { "divergenceProfile", "Abweichendes EPA-Profil" },
        { "boundsTitle", "Bounds" },
        { "actualizingList", "Selbst-aktualisierende Identit�ten" },
        { "circuitingList", "Umgebende Identit�ten" },
        { "redeemingList", "Redeeming Identities" },
        { "distantList", "Andere m�gliche Identit�ten" },
        { "writeTo", "Write To"},
        { "javaConsole", "Java Console"},
        { "processing", "Processing"},
        { "sentimentFormation", "Eindrucksbildung"},
        { "searchCutoff", "Search cut-off distance"},
        { "interactantsN", "Zahl der Interagierenden"},
        { "rememberN", "Number of events to remember"},
        { "impressions", "Fundamentals, impressions"},
        { "deflections", "Deflections"},
        { "actorEmotions", "Actor emotions"},
        { "objectEmotions", "Object emotions"},
        { "actorBehaviors", "Actor behaviors"},
        { "objectBehaviors", "Object behaviors"},
        { "actorLabels", "Actor labels"},
        { "objectLabels", "Object labels"},
        { "actorAttributes", "Actor attributes"},
        { "objectAttributes", "Object attributes"},
        { "chart", "Chart"},
        { "lists", "Lists"},
        { "verbalEvents", "Verbal events"},
        { "batchRuns", "Run events automatically"},
        { "keepRecords", "Record all events"},
        { "fromReidents", "From reidentifications"},
        { "fromTransients", "From transients"},
        { "eventProblemTitle", "Problem" },
        { "storeEventsError", new String[] {"Name des Akteurs nicht erkannt.", "Akteur hat keine Identit�t.", "Die Identit�t des Akterus ist nicht im W�rterbuch.", "Charakterz�ge / Emotionen des Akteurs sind nicht im W�rterbuch.", "Handlungen sind nicht im W�rterbuch.", "Name der Objektperson nicht erkannt.", "Objektperson hat keine Identit�t.", "Die Identit�t der Objektperson ist nicht im W�rterbuch.", "Charakterz�ge / Emotionen der Objektperson sind nicht im W�rterbuch.", "Zuviele W�rter in einer Zeile.", "Unbekanntes Zeichen.", "Zeile unvollst�ndig."} },
        { "empty", "_" },
        { "ok", "Okay" },
        { "earlierEvent", "Die vorhergehende Handlung muss implementiert werden." },
        { "isNot", "Fehler, die Handlung ist noch nicht implementiert" },
        { "deflection", "Deflection" },
        { "noEvents", "Keine Vorf�lle." },
        { "clickEvent", "Klicken Sie die erste Handlung an." },
        { "inputs", " Eingabe" },
        { "outcomes", " Ergebnisse" },
        { "filters", "Filter" },
        { "filterButton", "Weiter" },
        { "emotions", "Emotionen" },
        { "traits", "Charakterz�ge" },
        { "actorRoles", "Rolle des Akteurs" },
        { "objectRoles", "Rolle der Objektperson" },
        { "behaviors", "Handlungen" },
        { "responses", "Reaktionen" },
        { "filterProblemTitle", "Probleme mit dem Filter" },
        { "noEvent", "Um die Filter zu sehen, muss erst eine Handlung gew�hlt werden." },
        { "missingFilter", "In einer der Spalten ist nichts ausgew�hlt." },
        { "filterMsg1", "W�hlen Sie eine Kategorie f�r diese Begriffe." },
        { "filterMsg2", "W�hlen Sie mindestens eine blaue Option, falls vorhanden," },
        { "filterMsg3", "und mindestens eine schwarze Option in jeder Spalte." },
        { "resultsHeader", "Zusammenfassung der Ergebnisse." },
        { "realResponses", "Die beabsichtigte Reaktion der Objektperson" },
        { "equationImportProblemTitle", "Probleme die Gleichungen zu importieren" },
        { "missingTerm", "Fehlender Teil in der Gleichung:" },
        { "modifierIdentityError", "Fehler in den Charakterz�ge/Emotionen-Identit�ts Interaktionen." },
        { "notBasic", "Diese Funktion funktioniert nur im Fortgeschrittenen-Modus." },
        { "PosEval", "Angenehm, Gut" },
        { "PosPotn", "Gross, Schwer" },
        { "PosActiv", "Bewegt, Schnell" },
        { "NegEval", "Unangenehm, Schlecht" },
        { "NegPotn", "Klein, Leicht" },
        { "NegActiv", "Ruhig, Langsam" },
        { "infinitely", "extrem" },
        { "extremely", "sehr" },
        { "quite", "ziemlich" },
        { "slightly", "leicht" },
        { "neutral", "neutral" },
        { "termsOfUse", "Nutzungsbedingungen beachten! Alle Rechte vorbehalten: http://www.indiana.edu/~socpsy/ACT/legal.htm" },
        { "dicIdentities", " Lexikon der Identit�ten, N=" },
        { "dicBehaviors", " Lexikon der Handlungen, N=" },
        { "dicModifiers", " Lexikon der Charakterz�ge / Emotionen, N=" },
        { "dicSettings", " Lexikon der Situationen, N=" },
        { "dicMeans", "m�nnliche EPA Durchschnitte, weibliche EPA Durchschnitte:" },
        { "dicVars", "Varianz der m�nnlichen EPA Werte, Varianz der weiblichen EPA Werte:" },
        { "inputButton", "Eintr�ge importieren (siehe unten)" },
        { "exportButton", "Momentane Eintr�ge anzeigen" },
        { "eraseData", "Momentane Eintr�ge l�schen" },
        { "numberProblemTitle", "Number problem" },
        { "numberProblem", "Need a decimal number." },
        { "dicImportProblem", "Importieren Sie das Problem" },
        { "countProblem", "Falsche Anzahl von Ausdr�cken in einer Zeile." },
        { "badCharacters", "Falsche Zeichen irgendwo." },
        { "historyProblem", "Zu viele Interaktionen." }
  };

  public Object[][] getContents() {
    return contents;
  }
}